In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("/content/drive/MyDrive/Dataset/Corr_spearman.csv", index_col=0)
data

student  math  history  physics
0       A    70       90       30
1       B    78       94       38
2       C    90       79       59
3       D    87       86       55
4       E    84       84       49
5       F    86       83       55
6       G    91       88       75
7       H    74       92       36
8       I    83       76       43
9       J    85       75       53

In [3]:
data.count()

student    10
math       10
history    10
physics    10
dtype: int64

In [4]:
math = data.math
history = data.history
physics = data.physics

In [5]:
math_sort = -np.sort(-math)
history_sort = -np.sort(-history)
physics_sort = -np.sort(-physics)
print(math_sort)
print(history_sort)
print(physics_sort)

[91 90 87 86 85 84 83 78 74 70]
[94 92 90 88 86 84 83 79 76 75]
[75 59 55 55 53 49 43 38 36 30]


In [6]:
def find_rank(math):
  rank_column = np.array([])
  math_sort = -np.sort(-math)
  length = len(math)
  count=0
  cur_rank=0
  rank=0
  for i in range(length):
    j=0
    while(j<length):
      k=j
      while(k<length and math_sort[k] == math[i]):
        #rank_column=np.append(rank_column, k+1)
        cur_rank= cur_rank + (k+1)
        count=count+1
        k=k+1
      if(count>1): 
        rank=(cur_rank)/count
        rank_column=np.append(rank_column, rank)
        j=10

      elif(count==1):
        rank_column=np.append(rank_column, j+1)
      j=j+1
      rank=0
      count=0
      cur_rank=0
  return rank_column
      
math_rank = find_rank(math)
history_rank = find_rank(history)
physics_rank = find_rank(physics)
print(math_rank)
print(history_rank)
print(physics_rank)

[10.  8.  2.  3.  6.  4.  1.  9.  7.  5.]
[ 3.  1.  8.  5.  6.  7.  4.  2.  9. 10.]
[10.   8.   2.   3.5  6.   3.5  1.   9.   7.   5. ]


In [7]:
d = np.absolute(np.subtract(math_rank,physics_rank))
d_sqr = np.square(d)
print(d)
print(d_sqr)

[0.  0.  0.  0.5 0.  0.5 0.  0.  0.  0. ]
[0.   0.   0.   0.25 0.   0.25 0.   0.   0.   0.  ]


In [8]:
df=pd.DataFrame(list(zip(data.student,data.math,math_rank,data.history,history_rank,data.physics,physics_rank,d,d_sqr)),
                columns=['student','math','math_rank','history','history_rank','physics','physics_rank','d','d^2'])
df

student  math  math_rank  history  history_rank  physics  physics_rank    d  \
0       A    70       10.0       90           3.0       30          10.0  0.0   
1       B    78        8.0       94           1.0       38           8.0  0.0   
2       C    90        2.0       79           8.0       59           2.0  0.0   
3       D    87        3.0       86           5.0       55           3.5  0.5   
4       E    84        6.0       84           6.0       49           6.0  0.0   
5       F    86        4.0       83           7.0       55           3.5  0.5   
6       G    91        1.0       88           4.0       75           1.0  0.0   
7       H    74        9.0       92           2.0       36           9.0  0.0   
8       I    83        7.0       76           9.0       43           7.0  0.0   
9       J    85        5.0       75          10.0       53           5.0  0.0   

    d^2  
0  0.00  
1  0.00  
2  0.00  
3  0.25  
4  0.00  
5  0.25  
6  0.00  
7  0.00  
8  0.00  
9  0.00

In [9]:
sum_d = np.sum(d_sqr)
length = len(math)
print(sum_d)

0.5


In [10]:
r = 1 - ((6*sum_d)/ ((length**3)-length))
print("Spearman Rank Correlation: ", r)

Spearman Rank Correlation:  0.996969696969697


In [13]:
import scipy.stats
print("Spearman Rank Correlation Using Library: ",scipy.stats.spearmanr(math, physics)[0])

Spearman Rank Correlation Using Library:  0.996965091635306
